package boffbot;

import java.io.IOException;

/**
 * The main entry point of the BoffBot application.
 * BoffBot handles user interaction, command parsing, and task management.
 */
public class BoffBot {
    private Storage storage;
    private TaskList tasks;
    private Ui ui;

    /**
     * Constructs a BoffBot instance with a given file path for data storage.
     *
     * @param filePath The file path used to load and save tasks.
     */
    public BoffBot(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);
        try {
            tasks = new TaskList(storage.load());
        } catch (IOException | BoffBotException e) {
            ui.showMessage("Error loading data file: " + e.getMessage());
            tasks = new TaskList();
        }
    }

    /**
     * Processes a single user input and returns BoffBot's response.
     *<p>
     * This method serves as the main entry point for GUI-based interaction.
     * It delegates command handling to the {@link Parser} while collecting
     * all output messages generated via the {@link Ui}.
     *
     * @param input The user command entered via the GUI.
     * @return The response messages generated by BoffBot.
     */
    public String getResponse(String input) {
        try {
            Parser.parse(input, tasks, ui, storage);
            return ui.consumeOutput();
        } catch (Exception e) {
            return e.getMessage();
        }
    }

}
