package boffbot;

/**
 * Handles all user interface interactions such as displaying messages
 * and reading user input from the console.
 */
public class Ui {
    private StringBuilder output = new StringBuilder();


    public void showMessage(String msg) {
        output.append(msg).append("\n");
    }

    public void showTaskList(TaskList tasks) {
        if (tasks.size() == 0) {
            output.append("No tasks currently. Add a new task!\n");
            return;
        }

        output.append("Here are the tasks in your list:\n");
        for (int i = 0; i < tasks.size(); i++) {
            output.append((i + 1))
                    .append(". ")
                    .append(tasks.get(i))
                    .append("\n");
        }
    }

    /**
     * Returns all messages accumulated since the last call and clears the output buffer.
     * <p>
     * This method allows the GUI to retrieve responses generated by the bot
     * without relying on console output.
     *
     * @return A string containing all accumulated output messages.
     */
    public String consumeOutput() {
        String result = output.toString();
        output.setLength(0);
        return result;
    }
}
